### PR TITLE
Create Jenkins call job

### PR DESCRIPTION
**Pull request by robsonbittencourt**
Create gear structure. Add call job feature.

### CODE REVIEW

**Comment by robsonbittencourt** [comment]
@robsonrosa please make the code review. Still missing the tests, when ready I will send them here, but already feedback on the code

**Comment by robsonbittencourt** [comment]
@robsonrosa unit tests are ok here :smile:

**Comment by robsonrosa** [comment]
Excelent @robsonbittencourt ! The tests are awesome. I think that `getRecipient` could be a function in the hubot itself, but it can be done later. The use o speech in messages also can be done later.

**Comment by robsonbittencourt** [comment]
Changes ok, was even better.

**Pull request merged**
